[package]
name = "kodare/getgenvtesting"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
ReactRoblox = "jsdotlua/react-roblox@17.2.1"
React = "jsdotlua/react@17.2.1"